### ISSUE TITLE
How to use jRAPL

### ISSUE THREAD

**Issue by OcculterCoder** [kliu20/jRAPL#4]
Hi, actually i am facing problem to use jRAPL. In the readme file's Build section you have written to generate energy measurement and hardware counter measurement library i need to type the given commands. But would you please say exactly where i need to run it. I am totally confused. Thanks

**Comment by kliu20** [comment]
JRAPL is only supported on Linux, and cannot be on VM since it needs to
access the real registers. Just open the terminal on Linux and typed the
commands on readme file would be fine.

Kenan

**Comment by OcculterCoder** [comment]
Thanks for the info. I was using it on VM. Later, i will use it in real linux machine. One more question, do i need to do anything to import jRAPL library like .jar in java? Or the given commands are enough to start working with jRAPL? Please let me know. Thanks

**Comment by kliu20** [comment]
You're welcome. You will need put generated .so file and
EnergyCheckUtils.java (you can also write your own class to invoke these
APIs, just follow the routines in this class) in your project.

Kenan

**Comment by kyungwoh** [comment]
FYI, you will need sudo, even running java.

**Comment by OcculterCoder** [comment]
Hi, 
I am getting the following error...

CPUScaler.c:2:17: fatal error: jni.h: No such file or directory
compilation terminated.
In file included from msr.c:4:0:
msr.h:5:17: fatal error: jni.h: No such file or directory
compilation terminated.

I already have jni.h. But my program is not getting it. Please help.
